# Generated by Django 4.1.2 on 2022-10-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
